'use client'

export const dashboardStats = [
  {
    key: 'pending',
    label: 'Pending Orders',
    count: '0',
    tone: 'orange',
  },
  {
    key: 'completed',
    label: 'Completed Orders',
    count: '0',
    tone: 'green',
  },
  {
    key: 'downloaded',
    label: 'Downloaded Files',
    count: '0',
    tone: 'blue',
  },
  {
    key: 'cancelled',
    label: 'Cancelled Orders',
    count: '0',
    tone: 'red',
  },
]

export const recentOrders = [
  {
    id: 'ORD-00145',
    status: 'Pending',
    customerName: 'Aman Kumar',
    phone: '+91 98765 43210',
    fileName: 'Project_Report.pdf',
    pages: 12,
    copies: 2,
    type: 'B&W',
    size: 'A4',
    side: 'Double',
    price: '₹24.00',
    timestamp: 'Today, 10:30 AM',
    createdAt: '2026-07-14T10:30:00.000Z',
    variant: 'standard',
  },
  {
    id: 'ORD-00144',
    status: 'Pending',
    customerName: 'Neha Sharma',
    phone: '+91 87654 32109',
    fileName: 'Notes_Maths.pdf',
    pages: 8,
    copies: 2,
    type: 'Color',
    size: 'A4',
    side: 'Single',
    price: '₹12.00',
    timestamp: 'Today, 10:28 AM',
    createdAt: '2026-07-14T10:28:00.000Z',
    variant: 'standard',
  },
  {
    id: 'ORD-00143',
    status: 'Completed',
    customerName: 'Vivek Patil',
    phone: '+91 91234 56789',
    fileName: 'Assignment.docx',
    pages: 5,
    copies: 1,
    type: 'B&W',
    size: 'A4',
    side: 'Single',
    price: '₹5.00',
    timestamp: 'Today, 10:20 AM',
    createdAt: '2026-07-14T10:20:00.000Z',
    variant: 'standard',
  },
  {
    id: 'ORD-00142',
    status: 'Downloaded',
    customerName: 'Pooja Singh',
    phone: '+91 99887 76655',
    fileName: 'ID_Proof_Copy.pdf',
    pages: 2,
    copies: 1,
    type: 'Color',
    size: 'A4',
    side: 'Single',
    price: '₹6.00',
    timestamp: 'Today, 10:15 AM',
    createdAt: '2026-07-14T10:15:00.000Z',
    variant: 'talk',
  },
  {
    id: 'ORD-00141',
    status: 'Cancelled',
    customerName: 'Rohit Verma',
    phone: '+91 90909 09090',
    fileName: 'Fee_Receipt.pdf',
    pages: 3,
    copies: 1,
    type: 'B&W',
    size: 'A4',
    side: 'Single',
    price: '₹3.00',
    timestamp: 'Today, 10:05 AM',
    createdAt: '2026-07-14T10:05:00.000Z',
    variant: 'standard',
  },
]

export const bottomDockItems = [
  { key: 'profile', label: 'Profile', badge: null, href: '/shopkeeper/profile' },
  { key: 'settings', label: 'Settings', badge: null, href: '/shopkeeper/settings' },
  { key: 'subscription', label: 'Subscription', badge: null, href: '/shopkeeper/subscription' },
  { key: 'allOrders', label: 'Statistics & Analysis', badge: null, href: '/shopkeeper/statistics-and-analysis' },
  { key: 'pending', label: 'Pending', badge: null },
  { key: 'completed', label: 'Completed', badge: null },
  { key: 'downloaded', label: 'Downloaded', badge: null },
  { key: 'cancelled', label: 'Cancelled', badge: null },
  { key: 'customBill', label: 'Custom Bill', badge: null },
  { key: 'addOrder', label: 'Add order', badge: null, href: '/customer/language?shopkeeperAddOrder=true' },
  { key: 'coupon', label: 'Business network', badge: null, href: '/shopkeeper/business-network' },
  { key: 'printsmartAi', label: '🤖 AI Copilot', badge: null, href: '/shopkeeper/ai' },
]
